/**
 * Server Side Rendering
 */
import { APIGatewayEvent } from 'aws-lambda';
import * as React from 'react';
import { renderToString } from 'react-dom/server';

import App from '@src/App';
import ConfigContext from '@src/components/ConfigContext';
import config from '@src/server/config';
import html from '@src/server/html';
import { Stats } from '@src/server/types';

/**
 * Server-side rendering
 */
export default async function render(_event: APIGatewayEvent): Promise<string> {
  // The stats are generated by the Webpack Stats Plugin (`webpack-stats-plugin`)
  const stats = (await import('../../dist/stats.json')) as unknown as Stats;
  const content = renderToString(
    <ConfigContext.Provider value={config}>
      <App />
    </ConfigContext.Provider>,
  );
  return html({ stats, content, config });
}
