name: Deploy

on:
  push:
    branches:
      - 'main'
      - 'develop'

jobs:
  tests:
    uses: "./.github/workflows/test.yaml"
    secrets:
      AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
      AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"

  deploy:
    name: Deploy
    needs: [tests]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['21.6.1']
        pnpm: ['8.15.4']

    steps:
      - name: Checkout
        id: checkout_code
        uses: actions/checkout@v4

      - name: Get Stage
        id: get_stage
        shell: bash
        run: |
          if [ "${{ github.ref }}" == "refs/heads/develop" ]; then
            echo "stage=develop" >> $GITHUB_ENV
          elif [ "${{ github.ref }}" == "refs/heads/main"]; then
            echo "stage=production" >> $GITHUB_ENV
          else
            echo "stage=develop" >> $GITHUB_ENV
          fi

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: "${{ matrix.pnpm }}"

      - name: Setup Node
        id: setup_node
        uses: actions/setup-node@v4
        with:
          node-version: "${{ matrix.node }}"
          cache: "pnpm"

      - name: Install Serverless
        id: install_serverless
        run: pnpm install -g serverless

      - name: Install Packages
        id: install_packages
        run: pnpm install

      - name: Authenticate
        id: authenticate
        run: "sls config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}"

      - name: Deploy to AWS
        id: deploy_to_aws
        run: "sls deploy --conceal -s ${{ env.stage }} --region us-east-1 --verbose"
